### PR TITLE
Don't rewrite keypair on open when aren't new

### PR DESCRIPTION
**Pull request by noffle**
My first PR! Addresses #108.

### CODE REVIEW

**Comment by pfrazee** [comment]
huzzah!

**Comment by noffle** [comment]
Tweaks: `standard` doesn't like my human-readable formatting on the `missing` list.

**Comment by mafintosh** [comment]
Would be cool to add a test for that but I can do that for you :)

**Comment by noffle** [comment]
If the storage key isn't the same as the generated or constructor key, [it looks like an error case](https://github.com/mafintosh/hypercore/blob/master/index.js#L184). I'm not sure I understand the case where the constructor offers a secret key but a fresh public key is generated -- aren't keypairs codependent?

**Comment by mafintosh** [comment]
@noffle i meant the case where you are creating a fresh hypercore but providing both key+secretKey in the constructor. Then generated will be false but it needs to write them to storage still.

**Comment by mafintosh** [comment]
@noffle could be that your code already works for that. thats why we need a test for that case :)

**Comment by mafintosh** [comment]
here is an example of an existing storage test, https://github.com/mafintosh/hypercore/blob/master/test/basic.js#L70

**Comment by noffle** [comment]
I think I understand now. Thanks for explaining @mafintosh. :heart:

**Comment by noffle** [comment]
I think this fella is ready to :ship:!

**Comment by mafintosh** [comment]
\o/ 6.6.7

**Pull request merged**
