### PR TITLE
Add/encoding

### LINKED ISSUE #39: support value encoding
```
var core = hypercore(db, {
  valueEncoding: someAbstractEncoder // also support 'json' / 'utf-8' perhaps
})
```

### PR DESCRIPTION
**Pull request by juliangruber**
fixes #39 

needs refactoring etc, i was offline when i wrote this

@mafintosh what do you think?

### CODE REVIEW

**Comment by mafintosh** [comment]
@juliangruber looking great!! unsure why it's failing on travis (in a plane so cant debug)

**Comment by juliangruber** [comment]
fails because of...arrow syntax of course! :D 

Awesome, I'll get those points addressed :)

**Comment by juliangruber** [comment]
@mafintosh should be good now

**Comment by mafintosh** [comment]
👍 👍 👍 👍

**Comment by mafintosh** [comment]
4.11.0

**Comment by juliangruber** [comment]
schweeeet

**Pull request merged**
