### PR TITLE
downloaded function

### PR DESCRIPTION
**Pull request by e-e-e**
This is perhaps more complicated than I initially thought, but it is much more efficient than iterating over the individual bits. Basically I get the total by iterating over the byte range and tally the number of ones using a look up table. I tried to mirror your style as much as possible, but let me know if you have any suggestions how to make it better.

As for adding range option to `has` what were your thoughts. A boolean response if all bits are downloaded? If so we can add that easily with the help of this function too. I am just unsure how you were thinking to handle the args, would it expect an object {start: 0, end: n} or just assume that if you include a second arg that its a range, other wise just check individually. Let me know, and I will add it.

### CODE REVIEW

**Comment by mafintosh** [comment]
This is great! You can actually make this function even faster by using the bitfield index as well to skip over large sections of `1`/`0` bits but this is fine for now.

**Comment by mafintosh** [comment]
I think you should make another PR for `.has(start, [end])` btw. Then we can land this faster

**Comment by mafintosh** [comment]
Can I get you to add a test that uses the feed interface as well and tests the defaults?

**Comment by e-e-e** [comment]
I would be super curious how your bitfield index works - i did not quite get my head around it all.

**Comment by mafintosh** [comment]
6.4.0

**Pull request merged**
