### PR TITLE
Support onwrite hook

### PR DESCRIPTION
**Pull request by mafintosh**
``` js
var feed = hypercore('./feed', {
  onwrite: function (index, data, cb) {
    console.log('before write', index, data)
    cb()
  }
})

feed.append('hello world') // triggers the hook

// also triggered if data is written during replication
```

Needs docs and tests. Just testing this out for now

### CODE REVIEW

**Comment by pfrazee** [comment]
Seems good to me, what was the motivation for this?

**Comment by mafintosh** [comment]
@pfrazee for doing local indexing as data is coming in. think i use this to easily track latest files in hyperdrive

**Comment by fsteff** [comment]
Does this update the data if you pass it to the callback?

**Comment by mafintosh** [comment]
@fsteff we can make it overridable for sure by accepting a buffer in the cb (my usecase was different)

**Comment by mafintosh** [comment]
6.13.0

**Pull request merged**
