### PR TITLE
Add unreplicate()

### PR DESCRIPTION
**Pull request by pfrazee**
Closes https://github.com/mafintosh/hypercore/issues/48

### CODE REVIEW

**Comment by pfrazee** [comment]
The method signature here differs from hyperdrive's, so, if this is right, we'll need to update hyperdrive's usage.

**Comment by pfrazee** [comment]
weird, I wonder why standard didnt run on my tests. Investigating...

**Comment by pfrazee** [comment]
Whoops, my es6 is leaking

**Comment by pfrazee** [comment]
Ok ready for review

**Comment by mafintosh** [comment]
4.15.0

**Pull request merged**
