### PR TITLE
Add feed.has(start, [end])

### PR DESCRIPTION
**Pull request by e-e-e**
This is built on top of my last PR as it uses the bitfield.total function. As such the commit history has all the changes from that PR, but if https://github.com/mafintosh/hypercore/pull/101 is merged first I can rebase this one so the commit history is clean while including any other changes that might be needed on that PR.

I just wanted to open this up as I had time now. Let me know if there are any changes you would like made.

### CODE REVIEW

**Comment by mafintosh** [comment]
👍 👍 👍 Could you rebase master?

**Comment by e-e-e** [comment]
yep will do it now

**Comment by e-e-e** [comment]
@mafintosh rebased

**Comment by mafintosh** [comment]
6.5.0

**Pull request merged**
